# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wallet-ios-core' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wallet-ios-core
  pod 'Alamofire'
  pod 'Timepiece'
  pod 'TextFieldEffects'
  pod 'IQKeyboardManagerSwift'
  pod 'SnapKit'
  pod 'DZNEmptyDataSet'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'Socket.IO-Client-Swift'

  target 'wallet-ios-coreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
